project:
  type: website

website:
  title: "Yuhan Xiao"
  favicon: "images/favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: 'Home'
      - about.qmd
      - analysis.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    linkcolor: "#0F52BA"
    
execute:
  freeze: true  # never re-render during project render

editor: visual

